app/apps/reporting/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path

from reporting.views import (
    DocumentReport,
    ProjectReport,
    QuotasLeaderboard,
    ReportDetail,
    ReportList,
)

urlpatterns = [
    path('quotas/', ReportList.as_view(), name='report-list'),
    path('quotas/<int:pk>/', ReportDetail.as_view(), name='report-detail'),
    path('quotas/instance/', staff_member_required(QuotasLeaderboard.as_view()), name='quotas-leaderboard'),
    path('project/<str:slug>/reports/', ProjectReport.as_view(), name='project-report'),
    path('document/<int:pk>/reports/', DocumentReport.as_view(), name='document-report'),
]

app/escriptorium/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('imports.urls')),
    path('', include('users.urls')),
    path('', include('reporting.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('captcha/', include('captcha.urls')),
    path('', include('django_prometheus.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    try:
        import debug_toolbar
    except ImportError:
        pass
    else:
        urlpatterns += [path('__debug__/', include(debug_toolbar.urls)), ]

    # simulates a 500 to test error logging
    from django.views.defaults import server_error
    urlpatterns += [path('500/', server_error),
                    path('404/', TemplateView.as_view(template_name='404.html'))]

    # Serve static files in development
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/apps/reporting/models.py
from datetime import datetime, timezone

import psutil
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from escriptorium.celery import app

User = get_user_model()

# Dictionary to store CPU times for tasks.
task_cpu_times = {}


class TaskGroup(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    document = models.ForeignKey("core.Document", on_delete=models.CASCADE)
    task = models.CharField(max_length=256)

    # those 2 fields are only to be used in case of a single child task
    # with obvious steps, for example an import is a single celery task
    # but we have a set amount of files in the archive.
    # current = models.PositiveIntegerField(blank=True, null=True)
    # total = models.PositiveIntegerField(blank=True, null=True)

    class Meta:
        ordering = ["-created_at"]


class TaskReport(models.Model):
    WORKFLOW_STATE_QUEUED = 0
    WORKFLOW_STATE_STARTED = 1
    WORKFLOW_STATE_ERROR = 2
    WORKFLOW_STATE_DONE = 3
    WORKFLOW_STATE_CANCELED = 4
    WORKFLOW_STATE_CHOICES = (
        (WORKFLOW_STATE_QUEUED, _("Queued")),
        (WORKFLOW_STATE_STARTED, _("Running")),
        (WORKFLOW_STATE_ERROR, _("Crashed")),
        (WORKFLOW_STATE_DONE, _("Finished")),
        (WORKFLOW_STATE_CANCELED, _("Canceled")),
    )
    workflow_state = models.PositiveSmallIntegerField(
        default=WORKFLOW_STATE_QUEUED,
        choices=WORKFLOW_STATE_CHOICES
    )
    group = models.ForeignKey(TaskGroup, null=True, on_delete=models.SET_NULL)

    label = models.CharField(max_length=256)
    messages = models.TextField(blank=True)

    queued_at = models.DateTimeField(auto_now_add=True)
    started_at = models.DateTimeField(null=True)
    done_at = models.DateTimeField(null=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # celery task id
    task_id = models.CharField(max_length=64, blank=True, null=True)

    # shared_task method name
    method = models.CharField(max_length=512, blank=True, null=True)

    cpu_cost = models.FloatField(blank=True, null=True)
    gpu_cost = models.FloatField(blank=True, null=True)

    document = models.ForeignKey(
        "core.Document", blank=True, null=True, on_delete=models.SET_NULL, related_name='reports'
    )
    document_part = models.ForeignKey(
        "core.DocumentPart", blank=True, null=True, on_delete=models.SET_NULL, related_name='reports'
    )
    ocr_model = models.ForeignKey(
        "core.OcrModel", blank=True, null=True, on_delete=models.SET_NULL, related_name='reports'
    )

    def append(self, text, logger_fct=None):
        if logger_fct:
            logger_fct(text)

        self.messages += text + '\n'
        self.save()

    @property
    def uri(self):
        return reverse('report-detail', kwargs={'pk': self.pk})

    def start(self):
        self.workflow_state = self.WORKFLOW_STATE_STARTED
        self.started_at = datetime.now(timezone.utc)
        # Start tracking CPU time when the task starts.
        task_id = self.task_id
        task_cpu_times[task_id] = psutil.Process().cpu_times()
        self.save()

    def cancel(self, username):
        self.workflow_state = self.WORKFLOW_STATE_CANCELED
        self.done_at = datetime.now(timezone.utc)

        canceled_by = "anonymous"
        if username:
            canceled_by = f"user {username}"
        self.append(f"Canceled by {canceled_by}")

        app.control.revoke(self.task_id, terminate=True)
        self.save()

    def error(self, message):
        # unrecoverable error
        self.workflow_state = self.WORKFLOW_STATE_ERROR
        self.done_at = datetime.now(timezone.utc)
        self.append(message)
        self.save()

    def end(self, extra_links=None):
        self.workflow_state = self.WORKFLOW_STATE_DONE
        self.done_at = datetime.now(timezone.utc)
        self.save()

    def calc_cpu_cost(self):
        # No need to calculate the CPU usage if the task was canceled/crashed before even starting
        if not self.started_at:
            return

        task_id = self.task_id
        if task_id in task_cpu_times:
            start_cpu_times = task_cpu_times.pop(task_id)
            end_cpu_times = psutil.Process().cpu_times()
            user_cpu_time = end_cpu_times.user - start_cpu_times.user
            system_cpu_time = end_cpu_times.system - start_cpu_times.system
            self.cpu_cost = (user_cpu_time + system_cpu_time) / 60
        else:
            self.cpu_cost = 0
        self.save()

    def calc_gpu_cost(self):
        # No need to calculate the GPU usage if the task was canceled/crashed before even starting
        if not self.started_at:
            return

        task_duration = (self.done_at - self.started_at).total_seconds()
        self.gpu_cost = (task_duration * settings.GPU_COST) / 60
        self.save()

    def check_process_running(self):
        # Should only returns True if the actual process is still running.
        try:
            return app.AsyncResult(self.task_id).state == 'STARTED'
        except AttributeError:
            return False


TASK_FINAL_STATES = [TaskReport.WORKFLOW_STATE_ERROR, TaskReport.WORKFLOW_STATE_DONE, TaskReport.WORKFLOW_STATE_CANCELED]

app/apps/reporting/views.py
from collections import Counter, OrderedDict
from datetime import date, timedelta

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.postgres.aggregates.general import StringAgg
from django.core.paginator import Page, Paginator
from django.db.models import Avg, Count, DurationField, ExpressionWrapper, F, Q, Sum
from django.utils.functional import cached_property
from django.views.generic import DetailView, ListView
from django.views.generic.base import TemplateView

from core.models import Document, LineTranscription, Project
from reporting.models import TaskReport
from users.models import User


class ReportList(LoginRequiredMixin, ListView):
    model = TaskReport
    paginate_by = 20

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        cpu_usage = self.request.user.calc_cpu_usage()
        context['cpu_cost_last_week'] = cpu_usage
        gpu_usage = self.request.user.calc_gpu_usage()
        context['gpu_cost_last_week'] = gpu_usage

        disk_storage_limit = self.request.user.disk_storage_limit()
        context['enforce_disk_storage'] = not settings.DISABLE_QUOTAS and disk_storage_limit is not None
        if context['enforce_disk_storage']:
            context['disk_storage_used_percentage'] = min(round((self.request.user.calc_disk_usage() * 100) / disk_storage_limit, 2) if disk_storage_limit else 100, 100)

        cpu_minutes_limit = self.request.user.cpu_minutes_limit()
        context['enforce_cpu'] = not settings.DISABLE_QUOTAS and cpu_minutes_limit is not None
        if context['enforce_cpu']:
            context['cpu_minutes_used_percentage'] = min(round((cpu_usage * 100) / cpu_minutes_limit, 2) if cpu_minutes_limit else 100, 100)

        gpu_minutes_limit = self.request.user.gpu_minutes_limit()
        context['enforce_gpu'] = not settings.DISABLE_QUOTAS and gpu_minutes_limit is not None
        if context['enforce_gpu']:
            context['gpu_minutes_used_percentage'] = min(round((gpu_usage * 100) / gpu_minutes_limit, 2) if gpu_minutes_limit else 100, 100)

        return context

    def get_queryset(self):
        qs = super().get_queryset()

        blacklist = [
            'core.tasks.lossless_compression',
            'core.tasks.convert',
            'core.tasks.generate_part_thumbnails',
            'users.tasks.async_email',
            'core.tasks.recalculate_masks'
        ]

        return (qs.filter(user=self.request.user)
                  .exclude(method__in=blacklist)
                  .annotate(duration=ExpressionWrapper(F('done_at') - F('started_at'),
                                                       output_field=DurationField()))
                  .order_by('-queued_at'))


class ReportDetail(LoginRequiredMixin, DetailView):
    model = TaskReport
    context_object_name = 'report'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(user=self.request.user)


class CustomPaginator(Paginator):

    def __init__(self, *args, **kwargs):
        self._count = kwargs.pop('total')
        super(CustomPaginator, self).__init__(*args, **kwargs)

    @cached_property
    def count(self):
        return self._count

    def page(self, number):
        number = self.validate_number(number)
        return Page(self.object_list, number, self)


class QuotasLeaderboard(LoginRequiredMixin, TemplateView):
    template_name = "reporting/quotas_leaderboard.html"
    paginate_by = 20

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['enforce_quotas'] = not settings.DISABLE_QUOTAS

        try:
            page = int(self.request.GET.get('page', '1'))
        except ValueError:
            page = 1
        offset = (page - 1) * self.paginate_by

        today = date.today()
        filter_last_week = Q(taskreport__started_at__gte=today - timedelta(days=7))
        filter_last_day = Q(taskreport__started_at__gte=today - timedelta(days=1))
        runtime = ExpressionWrapper(
            F('taskreport__done_at') - F('taskreport__started_at'),
            output_field=DurationField()
        )

        qs = User.objects.all()
        results = list(
            qs.annotate(
                total_cpu_usage=Sum('taskreport__cpu_cost'),
                total_gpu_usage=Sum('taskreport__gpu_cost'),
                last_week_cpu_usage=Sum('taskreport__cpu_cost', filter=filter_last_week),
                last_week_gpu_usage=Sum('taskreport__gpu_cost', filter=filter_last_week),
                total_tasks=Count('taskreport'),
                total_runtime=Sum(runtime),
                last_week_tasks=Count('taskreport', filter=filter_last_week),
                last_week_runtime=Sum(runtime, filter=filter_last_week),
                last_day_tasks=Count('taskreport', filter=filter_last_day),
                last_day_runtime=Sum(runtime, filter=filter_last_day)
            ).order_by(F('total_runtime').desc(nulls_last=True))[offset:offset + self.paginate_by]
        )
        disk_usages_left = dict(qs.values('id').annotate(disk_usage=Sum('ocrmodel__file_size')).values_list('id', 'disk_usage'))
        disk_usages_right = dict(qs.values('id').annotate(disk_usage=Sum('document__parts__image_file_size')).values_list('id', 'disk_usage'))

        for user in results:
            user.disk_usage = (disk_usages_left[user.id] or 0) + (disk_usages_right[user.id] or 0)

        # Pagination
        paginator = CustomPaginator(results, self.paginate_by, total=qs.count())

        if page > paginator.num_pages:
            page = paginator.num_pages

        context['page_obj'] = paginator.page(page)
        context['is_paginated'] = paginator.num_pages > 1

        return context


class ProjectReport(LoginRequiredMixin, DetailView):
    template_name = 'reporting/project_reports.html'
    model = Project

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = self.object
        context['filters'] = self.request.GET.getlist('tags')
        context['vocabulary'] = self.request.GET.get('vocabulary')
        context['document_tags'] = list(self.object.document_tags.annotate(document_count=Count('tags_document', distinct=True)).values())
        context['part_count'] = self.get_aggregate_sum('part_count')
        context['part_lines_count'] = self.get_aggregate_sum('part_lines_count')
        context['documents_shared_with_users'] = self.get_aggregate_sum('documents_shared_with_users')
        context['documents_shared_with_groups'] = self.get_aggregate_sum('documents_shared_with_groups')
        context['part_lines_transcriptions'] = self.get_aggregate('part_lines_transcriptions')
        context['part_lines_typology'] = self.get_typology_count('part_lines_typology')
        context['part_block_typology'] = self.get_typology_count('part_block_typology')
        context['part_block_count'] = self.get_aggregate_sum('part_block_count')

        return context

    def get_object(self):
        project = Project.objects.get(slug=self.kwargs.get('slug'))
        self.documents = project.documents.exclude(workflow_state=Document.WORKFLOW_STATE_ARCHIVED)

        for tag in self.request.GET.getlist('tags'):
            self.documents = self.documents.filter(tags__name=tag)

        return project

    def get_aggregate_sum(self, field):
        document_list = self.documents

        if field == 'part_count':
            document_list = document_list.annotate(part_count=Count('parts', distinct=True))
        elif field == 'part_lines_count':
            document_list = document_list.annotate(part_lines_count=Count('parts__lines', distinct=True))
        elif field == 'documents_shared_with_users':
            document_list = document_list.annotate(documents_shared_with_users=Count('shared_with_users', distinct=True))
        elif field == 'documents_shared_with_groups':
            document_list = document_list.annotate(documents_shared_with_groups=Count('shared_with_groups', distinct=True))
        elif field == 'part_lines_typology':
            document_list = document_list.annotate(part_lines_typology=StringAgg('parts__lines__typology__name', delimiter='|'))
        elif field == 'part_block_typology':
            document_list = document_list.annotate(part_block_typology=StringAgg('parts__blocks__typology__name', delimiter='|'))
        elif field == 'part_block_count':
            document_list = document_list.annotate(part_block_count=Count('parts__blocks', distinct=True))

        sum = document_list.aggregate(data=Sum(field)).get('data')
        if sum is None:
            sum = 0
        return sum

    def get_aggregate(self, field, delimiter=' '):
        document_list = self.documents

        if field == 'part_lines_transcriptions':
            document_list = document_list.annotate(part_lines_transcriptions=StringAgg('parts__lines__transcriptions__content', delimiter=' '))
        elif field == 'part_lines_typology':
            document_list = document_list.annotate(part_lines_typology=StringAgg('parts__lines__typology__name', delimiter='|'))
        elif field == 'part_block_typology':
            document_list = document_list.annotate(part_block_typology=StringAgg('parts__blocks__typology__name', delimiter='|'))

        return document_list.aggregate(data=StringAgg(field, delimiter=delimiter)).get('data')

    def get_typology_count(self, field):
        value = self.get_aggregate(field, '|')
        return OrderedDict(Counter(value.split('|'))).items() if value else ''


class DocumentReport(LoginRequiredMixin, DetailView):
    template_name = 'reporting/document_report.html'
    model = Document

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # get form data
        transcription_pk = self.request.GET.get('transcription')

app/escriptorium/templates/reporting/document_report.html
{% extends 'core/document_nav.html' %}
{% load i18n static report bootstrap pagination cache %}
{% block head_title %}{% trans "Document report" %}{% endblock %}

{% block nav-reports-active %}active{% endblock %}

{% block extra_nav %}
{% endblock %}

{% block tab_content %}
    <div id="doc_report">
        <div class="row">
            <div class="col-2" id="document_list">
                <span>Transcription</span>
                <form method="GET">
                    <select id="document-transcriptions"
                            name="transcription"
                            title="Transcription"
                            class="form-control custom-select"
                            onchange="this.form.submit()">
                        <option value="all">All</option>
                        {% for transcription in all_transcriptions %}
                            <option
                                value="{{ transcription.pk }}"
                                {% if selected_transcription and selected_transcription.pk == transcription.pk %}selected{% endif %}>
                                {{ transcription.name }}
                            </option>
                        {% endfor %}
                    </select>
                </form>
            </div>
            <div class="col-10">
                <div class="mb-4 row justify-content-center"><h4>{% trans 'Data metrics' %}</h4></div>
                <div class="mb-4 row">
                    <div class="col">
                        <div class="card border-primary text-center h-100">
                            <i class="far fa-file-image card-header"></i>
                            <div class="card-body">
                                <h5 class="card-title">{% trans 'Total number of document parts' %}</h5>
                                <h2 class="card-title">{{ part_count|default:"0" }}</h2>
                                <p class="card-text">{% trans 'A document part corresponds to one image loaded within a document.' %}</p>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card border-primary text-center h-100">
                            <i class="far fa-file-image card-header"></i>
                            <div class="card-body">
                                <h5 class="card-title">{% trans 'Transcribed document parts' %}</h5>
                                <h2 class="card-title">{{ transcribed_part_count|default:"0" }}/{{ part_count|default:"0" }}</h2>
                                <p class="card-text">{% trans 'The number of transcribed images in the selected transcription(s).' %}</p>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card border-primary text-center h-100">
                            <i class="fas fa-stream card-header"></i>
                            <div class="card-body">
                                <h5 class="card-title">{% trans 'Average transcription confidence' %}</h5>
                                <h2 class="card-title">{{ avg_ocr_confidence|default:0|floatformat:2 }}</h2>
                                <p class="card-text">{% trans 'Confidence is an estimate of the automatic transcription model to approximate its own accuracy per character.' %}</p>
                                <p class="card-text">{% trans 'The validity of this figure will depend on specific cases and models and is not necessarily an indication of result quality.' %}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col">
                        <div class="card border-primary text-center">
                            <i class="fa fa-tags card-header"></i>
                            <div class="card-body">
                                <h5 class="card-title">
                                    {% trans 'Vocabulary' %}
                                    <a class="btn btn-primary fas fa-sync" title="{% trans 'Reload vocabulary' %}" href="?{% url_replace request 'vocabulary' 1 %}"></a>
                                </h5>
                                {% if vocabulary == "1" and part_lines_transcriptions|length > 0 %}
                                <table class="table">
                                    <tbody>
                                        <tr class="row">
                                            {% for item_v in part_lines_transcriptions|chunk_dict %}
                                                <td class="col">
                                                    {% for key, value in item_v.items %}
                                                        <table>
                                                            <tr>
                                                                {% for char, frequency in value %}
                                                                    <td>{{ char }}</td>
                                                                    <td>
                                                                    {% if frequency < 50 %}
                                                                        <span style="color: red;">{{ frequency }}</span>
                                                                    {% else %}
                                                                        <span>{{ frequency }}</span>
                                                                    {% endif %}
                                                                    </td>
                                                                {% endfor %}
                                                            </tr>
                                                        </table>
                                                    {% endfor %}
                                                </td>
                                            {% endfor %}
                                        </tr>
                                    <tbody>
                                </table>
                                {% elif vocabulary == "1" and part_lines_transcriptions|length == 0 %}
                                <p class="card-text">{% trans 'No vocabulary found in the selected transcription(s).' %}</p>
                                {% endif %}
                                <p class="card-text">{% trans 'The vocabulary is the list of all the characters currently used in the transcription of the document along with their frequency.' %}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/escriptorium/templates/reporting/taskreport_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
<div>
    <h5>{{ report.label }}</h5>
    <div>{% trans "Status:" %} {{ report.get_workflow_state_display }}</div>
    <div>{% trans "Queued at:" %} {{ report.queued_at }}</div>
    {% if report.workflow_state > 0 %}<div>{% trans "Started at:" %} {{ report.queued_at }}</div>{% endif %}
    {% if report.workflow_state > 1 %}<div>{% trans "Ended at:" %} {{ report.done_at }}</div>{% endif %}
    <div>{% trans "CPU usage" %}: {{ report.cpu_cost }}</div>
    <div>{% trans "GPU usage" %}: {{ report.gpu_cost }}</div>
    {% if report.messages %}<div class="jumbotron">{{ report.messages|linebreaks }}</div>{% endif %}
</div>
{% endblock %}

app/escriptorium/templates/reporting/taskreport_list.html
{% extends "base.html" %}
{% load i18n timedelta %}

{% block body %}
<h1>{% trans 'Task Usage' %}</h1>
<div>
    <div class="row mt-4 mb-3">
        <div class="col">
            <div class="card text-center">
                <div class="card-header">
                    {% trans "Disk usage" %}
                </div>
                <div class="card-body">
                    {% if enforce_disk_storage and not user.has_free_disk_storage %}
                    <div class="alert alert-danger small mb-2" role="alert">{% trans "You don't have any disk storage left" %}</div>
                    {% endif %}
                    <h5 class="card-title">
                        {{ user.calc_disk_usage|filesizeformat }}{% if enforce_disk_storage %}/{{ user.disk_storage_limit|filesizeformat }}{% endif %}
                    </h5>
                    <h6 class="card-subtitle mb-2 text-muted">{% trans "Calculated from your images and models" %}</h6>
                    {% if enforce_disk_storage %}
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="{{disk_storage_used_percentage}}" aria-valuemin="0" aria-valuemax="100" style="width: {{disk_storage_used_percentage}}%;">
                            {{ disk_storage_used_percentage }}% used
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card text-center">
                <div class="card-header">
                    {% trans "CPU usage" %}
                </div>
                <div class="card-body">
                    {% if enforce_cpu and not user.has_free_cpu_minutes %}
                    <div class="alert alert-danger small mb-2" role="alert">{% trans "You don't have any CPU minutes left" %}</div>
                    {% endif %}
                    <h5 class="card-title">
                        {{ cpu_cost_last_week|floatformat:3 }}{% if enforce_cpu %}/{{ user.cpu_minutes_limit }}{% endif %} CPU-min
                    </h5>
                    <h6 class="card-subtitle mb-2 text-muted">{% trans "CPU usage over the last week" %}</h6>
                    {% if enforce_cpu %}
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="{{cpu_minutes_used_percentage}}" aria-valuemin="0" aria-valuemax="100" style="width: {{cpu_minutes_used_percentage}}%;">
                            {{ cpu_minutes_used_percentage }}% used
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card text-center">
                <div class="card-header">
                    {% trans "GPU usage" %}
                </div>
                <div class="card-body">
                    {% if enforce_gpu and not user.has_free_gpu_minutes %}
                    <div class="alert alert-danger small mb-2" role="alert">{% trans "You don't have any GPU minutes left" %}</div>
                    {% endif %}
                    <h5 class="card-title">
                        {{ gpu_cost_last_week|floatformat:3 }}{% if enforce_gpu %}/{{ user.gpu_minutes_limit }}{% endif %} GPU-min
                    </h5>
                    <h6 class="card-subtitle mb-2 text-muted">{% trans "GPU usage over the last week" %}</h6>
                    {% if enforce_gpu %}
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="{{gpu_minutes_used_percentage}}" aria-valuemin="0" aria-valuemax="100" style="width: {{gpu_minutes_used_percentage}}%;">
                            {{ gpu_minutes_used_percentage }}% used
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="mb-3 text-center">
        <div class="alert alert-warning mb-2" role="alert">
            {% trans "CPU/GPU usage values also include automatic processing of the images on upload, those tasks aren't listed below." %}
        </div>
    </div>
    <table class="table table-hover">
        <tr>
            <th>{% trans "Task report" %}</th>
            <th>{% trans "Started at" %}</th>
            <th>{% trans "Done at" %}</th>
            <th>{% trans "Duration" %}</th>
            <th>{% trans "State" %}</th>
            <th>{% trans "CPU cost" %}</th>
            <th>{% trans "GPU cost" %}</th>
            <th></th>
        </tr>
        {% for report in object_list %}
        <tr>
            <td>{{ report.label }}</td>
            <td>{{ report.started_at }}</td>
            <td>{{ report.done_at }}</td>
            <td>{{ report.duration|format_timedelta }}</td>
            <td>
                {% with state=report.get_workflow_state_display %}
                {% if state == "Finished" %}
                <span class="badge badge-pill badge-success">{{ state }}</span>
                {% elif state == "Crashed" %}
                <span class="badge badge-pill badge-danger">{{ state }}</span>
                {% elif state == "Running" %}
                <span class="badge badge-pill badge-primary">{{ state }}</span>
                {% else %}
                <span class="badge badge-pill badge-secondary">{{ state }}</span>
                {% endif %}
                {% endwith %}
            </td>
            <td>
                {% if report.cpu_cost %}
                {{ report.cpu_cost|floatformat:2 }}
                {% else %}
                0
                {% endif %}
                CPU-min
            </td>
            <td>
                {% if report.gpu_cost %}
                {{ report.gpu_cost|floatformat:2 }}
                {% else %}
                0
                {% endif %}
                GPU-min
            </td>
            <td><a href="{% url 'report-detail' report.pk %}">{% trans "Details" %}</a></td>
        </tr>
        {% empty %}
        <tr><td>{% trans "You don't have any task report yet." %}</td></tr>
        {% endfor %}
    </table>

    {% include 'includes/pagination.html' %}
</div>
{% endblock %}